// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::craft_contribution_delta_type::CraftContributionDelta;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ApplyCraftProgressDeltasArgs {
    pub deltas: Vec<CraftContributionDelta>,
}

impl From<ApplyCraftProgressDeltasArgs> for super::Reducer {
    fn from(args: ApplyCraftProgressDeltasArgs) -> Self {
        Self::ApplyCraftProgressDeltas {
            deltas: args.deltas,
        }
    }
}

impl __sdk::InModule for ApplyCraftProgressDeltasArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `apply_craft_progress_deltas`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait apply_craft_progress_deltas {
    /// Request that the remote module invoke the reducer `apply_craft_progress_deltas` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`apply_craft_progress_deltas:apply_craft_progress_deltas_then`] to run a callback after the reducer completes.
    fn apply_craft_progress_deltas(
        &self,
        deltas: Vec<CraftContributionDelta>,
    ) -> __sdk::Result<()> {
        self.apply_craft_progress_deltas_then(deltas, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `apply_craft_progress_deltas` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn apply_craft_progress_deltas_then(
        &self,
        deltas: Vec<CraftContributionDelta>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl apply_craft_progress_deltas for super::RemoteReducers {
    fn apply_craft_progress_deltas_then(
        &self,
        deltas: Vec<CraftContributionDelta>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ApplyCraftProgressDeltasArgs { deltas }, callback)
    }
}
