// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_location_type::PlayerLocation;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BulkReplacePlayersArgs {
    pub region_id: u8,
    pub rows: Vec<PlayerLocation>,
    pub total: u32,
}

impl From<BulkReplacePlayersArgs> for super::Reducer {
    fn from(args: BulkReplacePlayersArgs) -> Self {
        Self::BulkReplacePlayers {
            region_id: args.region_id,
            rows: args.rows,
            total: args.total,
        }
    }
}

impl __sdk::InModule for BulkReplacePlayersArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `bulk_replace_players`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait bulk_replace_players {
    /// Request that the remote module invoke the reducer `bulk_replace_players` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`bulk_replace_players:bulk_replace_players_then`] to run a callback after the reducer completes.
    fn bulk_replace_players(
        &self,
        region_id: u8,
        rows: Vec<PlayerLocation>,
        total: u32,
    ) -> __sdk::Result<()> {
        self.bulk_replace_players_then(region_id, rows, total, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `bulk_replace_players` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn bulk_replace_players_then(
        &self,
        region_id: u8,
        rows: Vec<PlayerLocation>,
        total: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl bulk_replace_players for super::RemoteReducers {
    fn bulk_replace_players_then(
        &self,
        region_id: u8,
        rows: Vec<PlayerLocation>,
        total: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            BulkReplacePlayersArgs {
                region_id,
                rows,
                total,
            },
            callback,
        )
    }
}
