// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::resource_location_type::ResourceLocation;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BulkReplaceResourcesArgs {
    pub region_id: u8,
    pub rows: Vec<ResourceLocation>,
    pub total: u32,
}

impl From<BulkReplaceResourcesArgs> for super::Reducer {
    fn from(args: BulkReplaceResourcesArgs) -> Self {
        Self::BulkReplaceResources {
            region_id: args.region_id,
            rows: args.rows,
            total: args.total,
        }
    }
}

impl __sdk::InModule for BulkReplaceResourcesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `bulk_replace_resources`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait bulk_replace_resources {
    /// Request that the remote module invoke the reducer `bulk_replace_resources` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`bulk_replace_resources:bulk_replace_resources_then`] to run a callback after the reducer completes.
    fn bulk_replace_resources(
        &self,
        region_id: u8,
        rows: Vec<ResourceLocation>,
        total: u32,
    ) -> __sdk::Result<()> {
        self.bulk_replace_resources_then(region_id, rows, total, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `bulk_replace_resources` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn bulk_replace_resources_then(
        &self,
        region_id: u8,
        rows: Vec<ResourceLocation>,
        total: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl bulk_replace_resources for super::RemoteReducers {
    fn bulk_replace_resources_then(
        &self,
        region_id: u8,
        rows: Vec<ResourceLocation>,
        total: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            BulkReplaceResourcesArgs {
                region_id,
                rows,
                total,
            },
            callback,
        )
    }
}
