// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::claim_member_type::ClaimMember;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BulkReplaceClaimMembersArgs {
    pub region_id: u8,
    pub rows: Vec<ClaimMember>,
}

impl From<BulkReplaceClaimMembersArgs> for super::Reducer {
    fn from(args: BulkReplaceClaimMembersArgs) -> Self {
        Self::BulkReplaceClaimMembers {
            region_id: args.region_id,
            rows: args.rows,
        }
    }
}

impl __sdk::InModule for BulkReplaceClaimMembersArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `bulk_replace_claim_members`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait bulk_replace_claim_members {
    /// Request that the remote module invoke the reducer `bulk_replace_claim_members` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`bulk_replace_claim_members:bulk_replace_claim_members_then`] to run a callback after the reducer completes.
    fn bulk_replace_claim_members(
        &self,
        region_id: u8,
        rows: Vec<ClaimMember>,
    ) -> __sdk::Result<()> {
        self.bulk_replace_claim_members_then(region_id, rows, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `bulk_replace_claim_members` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn bulk_replace_claim_members_then(
        &self,
        region_id: u8,
        rows: Vec<ClaimMember>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl bulk_replace_claim_members for super::RemoteReducers {
    fn bulk_replace_claim_members_then(
        &self,
        region_id: u8,
        rows: Vec<ClaimMember>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(BulkReplaceClaimMembersArgs { region_id, rows }, callback)
    }
}
