// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::claim_info_type::ClaimInfo;
use super::claim_meta_type::ClaimMeta;
use super::claim_supply_type::ClaimSupply;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BulkReplaceClaimsArgs {
    pub region_id: u8,
    pub meta: Vec<ClaimMeta>,
    pub info: Vec<ClaimInfo>,
    pub supply: Vec<ClaimSupply>,
}

impl From<BulkReplaceClaimsArgs> for super::Reducer {
    fn from(args: BulkReplaceClaimsArgs) -> Self {
        Self::BulkReplaceClaims {
            region_id: args.region_id,
            meta: args.meta,
            info: args.info,
            supply: args.supply,
        }
    }
}

impl __sdk::InModule for BulkReplaceClaimsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `bulk_replace_claims`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait bulk_replace_claims {
    /// Request that the remote module invoke the reducer `bulk_replace_claims` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`bulk_replace_claims:bulk_replace_claims_then`] to run a callback after the reducer completes.
    fn bulk_replace_claims(
        &self,
        region_id: u8,
        meta: Vec<ClaimMeta>,
        info: Vec<ClaimInfo>,
        supply: Vec<ClaimSupply>,
    ) -> __sdk::Result<()> {
        self.bulk_replace_claims_then(region_id, meta, info, supply, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `bulk_replace_claims` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn bulk_replace_claims_then(
        &self,
        region_id: u8,
        meta: Vec<ClaimMeta>,
        info: Vec<ClaimInfo>,
        supply: Vec<ClaimSupply>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl bulk_replace_claims for super::RemoteReducers {
    fn bulk_replace_claims_then(
        &self,
        region_id: u8,
        meta: Vec<ClaimMeta>,
        info: Vec<ClaimInfo>,
        supply: Vec<ClaimSupply>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            BulkReplaceClaimsArgs {
                region_id,
                meta,
                info,
                supply,
            },
            callback,
        )
    }
}
