// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::claim_supply_type::ClaimSupply;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `claim_supply`.
///
/// Obtain a handle from the [`ClaimSupplyTableAccess::claim_supply`] method on [`super::RemoteTables`],
/// like `ctx.db.claim_supply()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.claim_supply().on_insert(...)`.
pub struct ClaimSupplyTableHandle<'ctx> {
    imp: __sdk::TableHandle<ClaimSupply>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `claim_supply`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ClaimSupplyTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ClaimSupplyTableHandle`], which mediates access to the table `claim_supply`.
    fn claim_supply(&self) -> ClaimSupplyTableHandle<'_>;
}

impl ClaimSupplyTableAccess for super::RemoteTables {
    fn claim_supply(&self) -> ClaimSupplyTableHandle<'_> {
        ClaimSupplyTableHandle {
            imp: self.imp.get_table::<ClaimSupply>("claim_supply"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ClaimSupplyInsertCallbackId(__sdk::CallbackId);
pub struct ClaimSupplyDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ClaimSupplyTableHandle<'ctx> {
    type Row = ClaimSupply;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ClaimSupply> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ClaimSupplyInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClaimSupplyInsertCallbackId {
        ClaimSupplyInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ClaimSupplyInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ClaimSupplyDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClaimSupplyDeleteCallbackId {
        ClaimSupplyDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ClaimSupplyDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ClaimSupplyUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ClaimSupplyTableHandle<'ctx> {
    type UpdateCallbackId = ClaimSupplyUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ClaimSupplyUpdateCallbackId {
        ClaimSupplyUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ClaimSupplyUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `claim_supply`,
/// which allows point queries on the field of the same name
/// via the [`ClaimSupplyEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.claim_supply().entity_id().find(...)`.
pub struct ClaimSupplyEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ClaimSupply, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ClaimSupplyTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `claim_supply`.
    pub fn entity_id(&self) -> ClaimSupplyEntityIdUnique<'ctx> {
        ClaimSupplyEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ClaimSupplyEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ClaimSupply> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ClaimSupply>("claim_supply");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ClaimSupply>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ClaimSupply>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ClaimSupply`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait claim_supplyQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ClaimSupply`.
    fn claim_supply(&self) -> __sdk::__query_builder::Table<ClaimSupply>;
}

impl claim_supplyQueryTableAccess for __sdk::QueryTableAccessor {
    fn claim_supply(&self) -> __sdk::__query_builder::Table<ClaimSupply> {
        __sdk::__query_builder::Table::new("claim_supply")
    }
}
