// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::claim_info_type::ClaimInfo;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `claim_info`.
///
/// Obtain a handle from the [`ClaimInfoTableAccess::claim_info`] method on [`super::RemoteTables`],
/// like `ctx.db.claim_info()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.claim_info().on_insert(...)`.
pub struct ClaimInfoTableHandle<'ctx> {
    imp: __sdk::TableHandle<ClaimInfo>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `claim_info`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ClaimInfoTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ClaimInfoTableHandle`], which mediates access to the table `claim_info`.
    fn claim_info(&self) -> ClaimInfoTableHandle<'_>;
}

impl ClaimInfoTableAccess for super::RemoteTables {
    fn claim_info(&self) -> ClaimInfoTableHandle<'_> {
        ClaimInfoTableHandle {
            imp: self.imp.get_table::<ClaimInfo>("claim_info"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ClaimInfoInsertCallbackId(__sdk::CallbackId);
pub struct ClaimInfoDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ClaimInfoTableHandle<'ctx> {
    type Row = ClaimInfo;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ClaimInfo> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ClaimInfoInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClaimInfoInsertCallbackId {
        ClaimInfoInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ClaimInfoInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ClaimInfoDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClaimInfoDeleteCallbackId {
        ClaimInfoDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ClaimInfoDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ClaimInfoUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ClaimInfoTableHandle<'ctx> {
    type UpdateCallbackId = ClaimInfoUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ClaimInfoUpdateCallbackId {
        ClaimInfoUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ClaimInfoUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `claim_info`,
/// which allows point queries on the field of the same name
/// via the [`ClaimInfoEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.claim_info().entity_id().find(...)`.
pub struct ClaimInfoEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ClaimInfo, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ClaimInfoTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `claim_info`.
    pub fn entity_id(&self) -> ClaimInfoEntityIdUnique<'ctx> {
        ClaimInfoEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ClaimInfoEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ClaimInfo> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ClaimInfo>("claim_info");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ClaimInfo>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ClaimInfo>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ClaimInfo`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait claim_infoQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ClaimInfo`.
    fn claim_info(&self) -> __sdk::__query_builder::Table<ClaimInfo>;
}

impl claim_infoQueryTableAccess for __sdk::QueryTableAccessor {
    fn claim_info(&self) -> __sdk::__query_builder::Table<ClaimInfo> {
        __sdk::__query_builder::Table::new("claim_info")
    }
}
