// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::claim_meta_type::ClaimMeta;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `claim_meta`.
///
/// Obtain a handle from the [`ClaimMetaTableAccess::claim_meta`] method on [`super::RemoteTables`],
/// like `ctx.db.claim_meta()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.claim_meta().on_insert(...)`.
pub struct ClaimMetaTableHandle<'ctx> {
    imp: __sdk::TableHandle<ClaimMeta>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `claim_meta`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ClaimMetaTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ClaimMetaTableHandle`], which mediates access to the table `claim_meta`.
    fn claim_meta(&self) -> ClaimMetaTableHandle<'_>;
}

impl ClaimMetaTableAccess for super::RemoteTables {
    fn claim_meta(&self) -> ClaimMetaTableHandle<'_> {
        ClaimMetaTableHandle {
            imp: self.imp.get_table::<ClaimMeta>("claim_meta"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ClaimMetaInsertCallbackId(__sdk::CallbackId);
pub struct ClaimMetaDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ClaimMetaTableHandle<'ctx> {
    type Row = ClaimMeta;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ClaimMeta> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ClaimMetaInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClaimMetaInsertCallbackId {
        ClaimMetaInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ClaimMetaInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ClaimMetaDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClaimMetaDeleteCallbackId {
        ClaimMetaDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ClaimMetaDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ClaimMetaUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ClaimMetaTableHandle<'ctx> {
    type UpdateCallbackId = ClaimMetaUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ClaimMetaUpdateCallbackId {
        ClaimMetaUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ClaimMetaUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `claim_meta`,
/// which allows point queries on the field of the same name
/// via the [`ClaimMetaEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.claim_meta().entity_id().find(...)`.
pub struct ClaimMetaEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ClaimMeta, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ClaimMetaTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `claim_meta`.
    pub fn entity_id(&self) -> ClaimMetaEntityIdUnique<'ctx> {
        ClaimMetaEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ClaimMetaEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ClaimMeta> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ClaimMeta>("claim_meta");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ClaimMeta>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ClaimMeta>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ClaimMeta`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait claim_metaQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ClaimMeta`.
    fn claim_meta(&self) -> __sdk::__query_builder::Table<ClaimMeta>;
}

impl claim_metaQueryTableAccess for __sdk::QueryTableAccessor {
    fn claim_meta(&self) -> __sdk::__query_builder::Table<ClaimMeta> {
        __sdk::__query_builder::Table::new("claim_meta")
    }
}
