// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ClaimSupply {
    pub entity_id: u64,
    pub region_id: u8,
    pub supplies: i32,
    pub num_tiles: u32,
    pub num_tile_neighbors: u32,
    pub building_maintenance: f32,
}

impl __sdk::InModule for ClaimSupply {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ClaimSupply`.
///
/// Provides typed access to columns for query building.
pub struct ClaimSupplyCols {
    pub entity_id: __sdk::__query_builder::Col<ClaimSupply, u64>,
    pub region_id: __sdk::__query_builder::Col<ClaimSupply, u8>,
    pub supplies: __sdk::__query_builder::Col<ClaimSupply, i32>,
    pub num_tiles: __sdk::__query_builder::Col<ClaimSupply, u32>,
    pub num_tile_neighbors: __sdk::__query_builder::Col<ClaimSupply, u32>,
    pub building_maintenance: __sdk::__query_builder::Col<ClaimSupply, f32>,
}

impl __sdk::__query_builder::HasCols for ClaimSupply {
    type Cols = ClaimSupplyCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ClaimSupplyCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            region_id: __sdk::__query_builder::Col::new(table_name, "region_id"),
            supplies: __sdk::__query_builder::Col::new(table_name, "supplies"),
            num_tiles: __sdk::__query_builder::Col::new(table_name, "num_tiles"),
            num_tile_neighbors: __sdk::__query_builder::Col::new(table_name, "num_tile_neighbors"),
            building_maintenance: __sdk::__query_builder::Col::new(
                table_name,
                "building_maintenance",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `ClaimSupply`.
///
/// Provides typed access to indexed columns for query building.
pub struct ClaimSupplyIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<ClaimSupply, u64>,
    pub region_id: __sdk::__query_builder::IxCol<ClaimSupply, u8>,
}

impl __sdk::__query_builder::HasIxCols for ClaimSupply {
    type IxCols = ClaimSupplyIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ClaimSupplyIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            region_id: __sdk::__query_builder::IxCol::new(table_name, "region_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ClaimSupply {}
