// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ClaimMember {
    pub entity_id: u64,
    pub region_id: u8,
    pub claim_entity_id: u64,
    pub player_entity_id: u64,
    pub build: bool,
    pub inventory: bool,
    pub officer: bool,
    pub co_owner: bool,
    pub owner: bool,
}

impl __sdk::InModule for ClaimMember {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ClaimMember`.
///
/// Provides typed access to columns for query building.
pub struct ClaimMemberCols {
    pub entity_id: __sdk::__query_builder::Col<ClaimMember, u64>,
    pub region_id: __sdk::__query_builder::Col<ClaimMember, u8>,
    pub claim_entity_id: __sdk::__query_builder::Col<ClaimMember, u64>,
    pub player_entity_id: __sdk::__query_builder::Col<ClaimMember, u64>,
    pub build: __sdk::__query_builder::Col<ClaimMember, bool>,
    pub inventory: __sdk::__query_builder::Col<ClaimMember, bool>,
    pub officer: __sdk::__query_builder::Col<ClaimMember, bool>,
    pub co_owner: __sdk::__query_builder::Col<ClaimMember, bool>,
    pub owner: __sdk::__query_builder::Col<ClaimMember, bool>,
}

impl __sdk::__query_builder::HasCols for ClaimMember {
    type Cols = ClaimMemberCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ClaimMemberCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            region_id: __sdk::__query_builder::Col::new(table_name, "region_id"),
            claim_entity_id: __sdk::__query_builder::Col::new(table_name, "claim_entity_id"),
            player_entity_id: __sdk::__query_builder::Col::new(table_name, "player_entity_id"),
            build: __sdk::__query_builder::Col::new(table_name, "build"),
            inventory: __sdk::__query_builder::Col::new(table_name, "inventory"),
            officer: __sdk::__query_builder::Col::new(table_name, "officer"),
            co_owner: __sdk::__query_builder::Col::new(table_name, "co_owner"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
        }
    }
}

/// Indexed column accessor struct for the table `ClaimMember`.
///
/// Provides typed access to indexed columns for query building.
pub struct ClaimMemberIxCols {
    pub claim_entity_id: __sdk::__query_builder::IxCol<ClaimMember, u64>,
    pub entity_id: __sdk::__query_builder::IxCol<ClaimMember, u64>,
    pub player_entity_id: __sdk::__query_builder::IxCol<ClaimMember, u64>,
    pub region_id: __sdk::__query_builder::IxCol<ClaimMember, u8>,
}

impl __sdk::__query_builder::HasIxCols for ClaimMember {
    type IxCols = ClaimMemberIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ClaimMemberIxCols {
            claim_entity_id: __sdk::__query_builder::IxCol::new(table_name, "claim_entity_id"),
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            player_entity_id: __sdk::__query_builder::IxCol::new(table_name, "player_entity_id"),
            region_id: __sdk::__query_builder::IxCol::new(table_name, "region_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ClaimMember {}
