// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ClaimInfo {
    pub entity_id: u64,
    pub region_id: u8,
    pub bank: bool,
    pub marketplace: bool,
    pub waystone: bool,
    pub research: Vec<i32>,
}

impl __sdk::InModule for ClaimInfo {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ClaimInfo`.
///
/// Provides typed access to columns for query building.
pub struct ClaimInfoCols {
    pub entity_id: __sdk::__query_builder::Col<ClaimInfo, u64>,
    pub region_id: __sdk::__query_builder::Col<ClaimInfo, u8>,
    pub bank: __sdk::__query_builder::Col<ClaimInfo, bool>,
    pub marketplace: __sdk::__query_builder::Col<ClaimInfo, bool>,
    pub waystone: __sdk::__query_builder::Col<ClaimInfo, bool>,
    pub research: __sdk::__query_builder::Col<ClaimInfo, Vec<i32>>,
}

impl __sdk::__query_builder::HasCols for ClaimInfo {
    type Cols = ClaimInfoCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ClaimInfoCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            region_id: __sdk::__query_builder::Col::new(table_name, "region_id"),
            bank: __sdk::__query_builder::Col::new(table_name, "bank"),
            marketplace: __sdk::__query_builder::Col::new(table_name, "marketplace"),
            waystone: __sdk::__query_builder::Col::new(table_name, "waystone"),
            research: __sdk::__query_builder::Col::new(table_name, "research"),
        }
    }
}

/// Indexed column accessor struct for the table `ClaimInfo`.
///
/// Provides typed access to indexed columns for query building.
pub struct ClaimInfoIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<ClaimInfo, u64>,
    pub region_id: __sdk::__query_builder::IxCol<ClaimInfo, u8>,
}

impl __sdk::__query_builder::HasIxCols for ClaimInfo {
    type IxCols = ClaimInfoIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ClaimInfoIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            region_id: __sdk::__query_builder::IxCol::new(table_name, "region_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ClaimInfo {}
