// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::claim_member_type::ClaimMember;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `claim_member`.
///
/// Obtain a handle from the [`ClaimMemberTableAccess::claim_member`] method on [`super::RemoteTables`],
/// like `ctx.db.claim_member()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.claim_member().on_insert(...)`.
pub struct ClaimMemberTableHandle<'ctx> {
    imp: __sdk::TableHandle<ClaimMember>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `claim_member`.
pub struct ClaimMemberTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ClaimMemberTableAccessor {
    type Row = ClaimMember;
    type Handle<'db> = ClaimMemberTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.claim_member()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `claim_member`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ClaimMemberTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ClaimMemberTableHandle`], which mediates access to the table `claim_member`.
    fn claim_member(&self) -> ClaimMemberTableHandle<'_>;
}

impl ClaimMemberTableAccess for super::RemoteTables {
    fn claim_member(&self) -> ClaimMemberTableHandle<'_> {
        ClaimMemberTableHandle {
            imp: self.imp.get_table::<ClaimMember>("claim_member"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ClaimMemberInsertCallbackId(__sdk::CallbackId);
pub struct ClaimMemberDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ClaimMemberTableHandle<'ctx> {
    type Row = ClaimMember;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ClaimMember> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for ClaimMemberTableHandle<'ctx> {
    type Row = ClaimMember;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ClaimMember> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ClaimMemberInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClaimMemberInsertCallbackId {
        ClaimMemberInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ClaimMemberInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ClaimMemberDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClaimMemberDeleteCallbackId {
        ClaimMemberDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ClaimMemberDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ClaimMemberTableHandle<'ctx> {
    type InsertCallbackId = ClaimMemberInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClaimMemberInsertCallbackId {
        ClaimMemberInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ClaimMemberInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ClaimMemberTableHandle<'ctx> {
    type DeleteCallbackId = ClaimMemberDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClaimMemberDeleteCallbackId {
        ClaimMemberDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ClaimMemberDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ClaimMemberUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ClaimMemberTableHandle<'ctx> {
    type UpdateCallbackId = ClaimMemberUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ClaimMemberUpdateCallbackId {
        ClaimMemberUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ClaimMemberUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for ClaimMemberTableHandle<'ctx> {
    type UpdateCallbackId = ClaimMemberUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ClaimMemberUpdateCallbackId {
        ClaimMemberUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ClaimMemberUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `claim_member`,
/// which allows point queries on the field of the same name
/// via the [`ClaimMemberEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.claim_member().entity_id().find(...)`.
pub struct ClaimMemberEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ClaimMember, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ClaimMemberTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `claim_member`.
    pub fn entity_id(&self) -> ClaimMemberEntityIdUnique<'ctx> {
        ClaimMemberEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ClaimMemberEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ClaimMember> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ClaimMember>("claim_member");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ClaimMember>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ClaimMember>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ClaimMember`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait claim_memberQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ClaimMember`.
    fn claim_member(&self) -> __sdk::__query_builder::Table<ClaimMember>;
}

impl claim_memberQueryTableAccess for __sdk::QueryTableAccessor {
    fn claim_member(&self) -> __sdk::__query_builder::Table<ClaimMember> {
        __sdk::__query_builder::Table::new("claim_member")
    }
}
