// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ClaimMeta {
    pub entity_id: u64,
    pub region_id: u8,
    pub x: i32,
    pub z: i32,
    pub building_desc_id: i32,
}

impl __sdk::InModule for ClaimMeta {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ClaimMeta`.
///
/// Provides typed access to columns for query building.
pub struct ClaimMetaCols {
    pub entity_id: __sdk::__query_builder::Col<ClaimMeta, u64>,
    pub region_id: __sdk::__query_builder::Col<ClaimMeta, u8>,
    pub x: __sdk::__query_builder::Col<ClaimMeta, i32>,
    pub z: __sdk::__query_builder::Col<ClaimMeta, i32>,
    pub building_desc_id: __sdk::__query_builder::Col<ClaimMeta, i32>,
}

impl __sdk::__query_builder::HasCols for ClaimMeta {
    type Cols = ClaimMetaCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ClaimMetaCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            region_id: __sdk::__query_builder::Col::new(table_name, "region_id"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            building_desc_id: __sdk::__query_builder::Col::new(table_name, "building_desc_id"),
        }
    }
}

/// Indexed column accessor struct for the table `ClaimMeta`.
///
/// Provides typed access to indexed columns for query building.
pub struct ClaimMetaIxCols {
    pub building_desc_id: __sdk::__query_builder::IxCol<ClaimMeta, i32>,
    pub entity_id: __sdk::__query_builder::IxCol<ClaimMeta, u64>,
    pub region_id: __sdk::__query_builder::IxCol<ClaimMeta, u8>,
}

impl __sdk::__query_builder::HasIxCols for ClaimMeta {
    type IxCols = ClaimMetaIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ClaimMetaIxCols {
            building_desc_id: __sdk::__query_builder::IxCol::new(table_name, "building_desc_id"),
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            region_id: __sdk::__query_builder::IxCol::new(table_name, "region_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ClaimMeta {}
