// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::craft_progress_type::CraftProgress;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `craft_progress`.
///
/// Obtain a handle from the [`CraftProgressTableAccess::craft_progress`] method on [`super::RemoteTables`],
/// like `ctx.db.craft_progress()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.craft_progress().on_insert(...)`.
pub struct CraftProgressTableHandle<'ctx> {
    imp: __sdk::TableHandle<CraftProgress>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `craft_progress`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CraftProgressTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CraftProgressTableHandle`], which mediates access to the table `craft_progress`.
    fn craft_progress(&self) -> CraftProgressTableHandle<'_>;
}

impl CraftProgressTableAccess for super::RemoteTables {
    fn craft_progress(&self) -> CraftProgressTableHandle<'_> {
        CraftProgressTableHandle {
            imp: self.imp.get_table::<CraftProgress>("craft_progress"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CraftProgressInsertCallbackId(__sdk::CallbackId);
pub struct CraftProgressDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CraftProgressTableHandle<'ctx> {
    type Row = CraftProgress;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CraftProgress> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CraftProgressInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CraftProgressInsertCallbackId {
        CraftProgressInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CraftProgressInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CraftProgressDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CraftProgressDeleteCallbackId {
        CraftProgressDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CraftProgressDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CraftProgressUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CraftProgressTableHandle<'ctx> {
    type UpdateCallbackId = CraftProgressUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CraftProgressUpdateCallbackId {
        CraftProgressUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CraftProgressUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `craft_progress`,
/// which allows point queries on the field of the same name
/// via the [`CraftProgressEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.craft_progress().entity_id().find(...)`.
pub struct CraftProgressEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CraftProgress, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CraftProgressTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `craft_progress`.
    pub fn entity_id(&self) -> CraftProgressEntityIdUnique<'ctx> {
        CraftProgressEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CraftProgressEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CraftProgress> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CraftProgress>("craft_progress");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CraftProgress>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CraftProgress>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CraftProgress`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait craft_progressQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CraftProgress`.
    fn craft_progress(&self) -> __sdk::__query_builder::Table<CraftProgress>;
}

impl craft_progressQueryTableAccess for __sdk::QueryTableAccessor {
    fn craft_progress(&self) -> __sdk::__query_builder::Table<CraftProgress> {
        __sdk::__query_builder::Table::new("craft_progress")
    }
}
