// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::craft_contribution_type::CraftContribution;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `craft_contribution`.
///
/// Obtain a handle from the [`CraftContributionTableAccess::craft_contribution`] method on [`super::RemoteTables`],
/// like `ctx.db.craft_contribution()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.craft_contribution().on_insert(...)`.
pub struct CraftContributionTableHandle<'ctx> {
    imp: __sdk::TableHandle<CraftContribution>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `craft_contribution`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CraftContributionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CraftContributionTableHandle`], which mediates access to the table `craft_contribution`.
    fn craft_contribution(&self) -> CraftContributionTableHandle<'_>;
}

impl CraftContributionTableAccess for super::RemoteTables {
    fn craft_contribution(&self) -> CraftContributionTableHandle<'_> {
        CraftContributionTableHandle {
            imp: self
                .imp
                .get_table::<CraftContribution>("craft_contribution"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CraftContributionInsertCallbackId(__sdk::CallbackId);
pub struct CraftContributionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CraftContributionTableHandle<'ctx> {
    type Row = CraftContribution;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CraftContribution> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CraftContributionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CraftContributionInsertCallbackId {
        CraftContributionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CraftContributionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CraftContributionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CraftContributionDeleteCallbackId {
        CraftContributionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CraftContributionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CraftContributionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CraftContributionTableHandle<'ctx> {
    type UpdateCallbackId = CraftContributionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CraftContributionUpdateCallbackId {
        CraftContributionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CraftContributionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `craft_contribution`,
/// which allows point queries on the field of the same name
/// via the [`CraftContributionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.craft_contribution().id().find(...)`.
pub struct CraftContributionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CraftContribution, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CraftContributionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `craft_contribution`.
    pub fn id(&self) -> CraftContributionIdUnique<'ctx> {
        CraftContributionIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CraftContributionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CraftContribution> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CraftContribution>("craft_contribution");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CraftContribution>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CraftContribution>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CraftContribution`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait craft_contributionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CraftContribution`.
    fn craft_contribution(&self) -> __sdk::__query_builder::Table<CraftContribution>;
}

impl craft_contributionQueryTableAccess for __sdk::QueryTableAccessor {
    fn craft_contribution(&self) -> __sdk::__query_builder::Table<CraftContribution> {
        __sdk::__query_builder::Table::new("craft_contribution")
    }
}
