// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CraftProgress {
    pub entity_id: u64,
    pub last_seen: __sdk::Timestamp,
    pub progress: i32,
}

impl __sdk::InModule for CraftProgress {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CraftProgress`.
///
/// Provides typed access to columns for query building.
pub struct CraftProgressCols {
    pub entity_id: __sdk::__query_builder::Col<CraftProgress, u64>,
    pub last_seen: __sdk::__query_builder::Col<CraftProgress, __sdk::Timestamp>,
    pub progress: __sdk::__query_builder::Col<CraftProgress, i32>,
}

impl __sdk::__query_builder::HasCols for CraftProgress {
    type Cols = CraftProgressCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CraftProgressCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            last_seen: __sdk::__query_builder::Col::new(table_name, "last_seen"),
            progress: __sdk::__query_builder::Col::new(table_name, "progress"),
        }
    }
}

/// Indexed column accessor struct for the table `CraftProgress`.
///
/// Provides typed access to indexed columns for query building.
pub struct CraftProgressIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<CraftProgress, u64>,
}

impl __sdk::__query_builder::HasIxCols for CraftProgress {
    type IxCols = CraftProgressIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CraftProgressIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CraftProgress {}
