// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CraftContribution {
    pub id: u64,
    pub craft_id: u64,
    pub player_id: u64,
    pub contribution: i32,
}

impl __sdk::InModule for CraftContribution {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CraftContribution`.
///
/// Provides typed access to columns for query building.
pub struct CraftContributionCols {
    pub id: __sdk::__query_builder::Col<CraftContribution, u64>,
    pub craft_id: __sdk::__query_builder::Col<CraftContribution, u64>,
    pub player_id: __sdk::__query_builder::Col<CraftContribution, u64>,
    pub contribution: __sdk::__query_builder::Col<CraftContribution, i32>,
}

impl __sdk::__query_builder::HasCols for CraftContribution {
    type Cols = CraftContributionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CraftContributionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            craft_id: __sdk::__query_builder::Col::new(table_name, "craft_id"),
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            contribution: __sdk::__query_builder::Col::new(table_name, "contribution"),
        }
    }
}

/// Indexed column accessor struct for the table `CraftContribution`.
///
/// Provides typed access to indexed columns for query building.
pub struct CraftContributionIxCols {
    pub craft_id: __sdk::__query_builder::IxCol<CraftContribution, u64>,
    pub id: __sdk::__query_builder::IxCol<CraftContribution, u64>,
}

impl __sdk::__query_builder::HasIxCols for CraftContribution {
    type IxCols = CraftContributionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CraftContributionIxCols {
            craft_id: __sdk::__query_builder::IxCol::new(table_name, "craft_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CraftContribution {}
