// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::craft_meta_type::CraftMeta;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `craft_meta`.
///
/// Obtain a handle from the [`CraftMetaTableAccess::craft_meta`] method on [`super::RemoteTables`],
/// like `ctx.db.craft_meta()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.craft_meta().on_insert(...)`.
pub struct CraftMetaTableHandle<'ctx> {
    imp: __sdk::TableHandle<CraftMeta>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `craft_meta`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CraftMetaTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CraftMetaTableHandle`], which mediates access to the table `craft_meta`.
    fn craft_meta(&self) -> CraftMetaTableHandle<'_>;
}

impl CraftMetaTableAccess for super::RemoteTables {
    fn craft_meta(&self) -> CraftMetaTableHandle<'_> {
        CraftMetaTableHandle {
            imp: self.imp.get_table::<CraftMeta>("craft_meta"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CraftMetaInsertCallbackId(__sdk::CallbackId);
pub struct CraftMetaDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CraftMetaTableHandle<'ctx> {
    type Row = CraftMeta;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CraftMeta> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CraftMetaInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CraftMetaInsertCallbackId {
        CraftMetaInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CraftMetaInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CraftMetaDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CraftMetaDeleteCallbackId {
        CraftMetaDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CraftMetaDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CraftMetaUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CraftMetaTableHandle<'ctx> {
    type UpdateCallbackId = CraftMetaUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CraftMetaUpdateCallbackId {
        CraftMetaUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CraftMetaUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `craft_meta`,
/// which allows point queries on the field of the same name
/// via the [`CraftMetaEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.craft_meta().entity_id().find(...)`.
pub struct CraftMetaEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CraftMeta, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CraftMetaTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `craft_meta`.
    pub fn entity_id(&self) -> CraftMetaEntityIdUnique<'ctx> {
        CraftMetaEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CraftMetaEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CraftMeta> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CraftMeta>("craft_meta");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CraftMeta>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CraftMeta>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CraftMeta`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait craft_metaQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CraftMeta`.
    fn craft_meta(&self) -> __sdk::__query_builder::Table<CraftMeta>;
}

impl craft_metaQueryTableAccess for __sdk::QueryTableAccessor {
    fn craft_meta(&self) -> __sdk::__query_builder::Table<CraftMeta> {
        __sdk::__query_builder::Table::new("craft_meta")
    }
}
