// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CraftMeta {
    pub entity_id: u64,
    pub owner_entity_id: u64,
    pub claim_entity_id: u64,
    pub building_entity_id: u64,
    pub first_seen: __sdk::Timestamp,
    pub recipe_id: i32,
    pub count: i32,
    pub region_id: u8,
    pub public: bool,
}

impl __sdk::InModule for CraftMeta {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CraftMeta`.
///
/// Provides typed access to columns for query building.
pub struct CraftMetaCols {
    pub entity_id: __sdk::__query_builder::Col<CraftMeta, u64>,
    pub owner_entity_id: __sdk::__query_builder::Col<CraftMeta, u64>,
    pub claim_entity_id: __sdk::__query_builder::Col<CraftMeta, u64>,
    pub building_entity_id: __sdk::__query_builder::Col<CraftMeta, u64>,
    pub first_seen: __sdk::__query_builder::Col<CraftMeta, __sdk::Timestamp>,
    pub recipe_id: __sdk::__query_builder::Col<CraftMeta, i32>,
    pub count: __sdk::__query_builder::Col<CraftMeta, i32>,
    pub region_id: __sdk::__query_builder::Col<CraftMeta, u8>,
    pub public: __sdk::__query_builder::Col<CraftMeta, bool>,
}

impl __sdk::__query_builder::HasCols for CraftMeta {
    type Cols = CraftMetaCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CraftMetaCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            owner_entity_id: __sdk::__query_builder::Col::new(table_name, "owner_entity_id"),
            claim_entity_id: __sdk::__query_builder::Col::new(table_name, "claim_entity_id"),
            building_entity_id: __sdk::__query_builder::Col::new(table_name, "building_entity_id"),
            first_seen: __sdk::__query_builder::Col::new(table_name, "first_seen"),
            recipe_id: __sdk::__query_builder::Col::new(table_name, "recipe_id"),
            count: __sdk::__query_builder::Col::new(table_name, "count"),
            region_id: __sdk::__query_builder::Col::new(table_name, "region_id"),
            public: __sdk::__query_builder::Col::new(table_name, "public"),
        }
    }
}

/// Indexed column accessor struct for the table `CraftMeta`.
///
/// Provides typed access to indexed columns for query building.
pub struct CraftMetaIxCols {
    pub claim_entity_id: __sdk::__query_builder::IxCol<CraftMeta, u64>,
    pub entity_id: __sdk::__query_builder::IxCol<CraftMeta, u64>,
    pub owner_entity_id: __sdk::__query_builder::IxCol<CraftMeta, u64>,
}

impl __sdk::__query_builder::HasIxCols for CraftMeta {
    type IxCols = CraftMetaIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CraftMetaIxCols {
            claim_entity_id: __sdk::__query_builder::IxCol::new(table_name, "claim_entity_id"),
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            owner_entity_id: __sdk::__query_builder::IxCol::new(table_name, "owner_entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CraftMeta {}
