// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteRegionsArgs {
    pub regions: Option<Vec<u8>>,
}

impl From<DeleteRegionsArgs> for super::Reducer {
    fn from(args: DeleteRegionsArgs) -> Self {
        Self::DeleteRegions {
            regions: args.regions,
        }
    }
}

impl __sdk::InModule for DeleteRegionsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `delete_regions`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait delete_regions {
    /// Request that the remote module invoke the reducer `delete_regions` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`delete_regions:delete_regions_then`] to run a callback after the reducer completes.
    fn delete_regions(&self, regions: Option<Vec<u8>>) -> __sdk::Result<()> {
        self.delete_regions_then(regions, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `delete_regions` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn delete_regions_then(
        &self,
        regions: Option<Vec<u8>>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl delete_regions for super::RemoteReducers {
    fn delete_regions_then(
        &self,
        regions: Option<Vec<u8>>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DeleteRegionsArgs { regions }, callback)
    }
}
