// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::enemy_location_type::EnemyLocation;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `enemy_location`.
///
/// Obtain a handle from the [`EnemyLocationTableAccess::enemy_location`] method on [`super::RemoteTables`],
/// like `ctx.db.enemy_location()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.enemy_location().on_insert(...)`.
pub struct EnemyLocationTableHandle<'ctx> {
    imp: __sdk::TableHandle<EnemyLocation>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `enemy_location`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EnemyLocationTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EnemyLocationTableHandle`], which mediates access to the table `enemy_location`.
    fn enemy_location(&self) -> EnemyLocationTableHandle<'_>;
}

impl EnemyLocationTableAccess for super::RemoteTables {
    fn enemy_location(&self) -> EnemyLocationTableHandle<'_> {
        EnemyLocationTableHandle {
            imp: self.imp.get_table::<EnemyLocation>("enemy_location"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EnemyLocationInsertCallbackId(__sdk::CallbackId);
pub struct EnemyLocationDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for EnemyLocationTableHandle<'ctx> {
    type Row = EnemyLocation;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EnemyLocation> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EnemyLocationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EnemyLocationInsertCallbackId {
        EnemyLocationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EnemyLocationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EnemyLocationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EnemyLocationDeleteCallbackId {
        EnemyLocationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EnemyLocationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct EnemyLocationUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for EnemyLocationTableHandle<'ctx> {
    type UpdateCallbackId = EnemyLocationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EnemyLocationUpdateCallbackId {
        EnemyLocationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EnemyLocationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `enemy_location`,
/// which allows point queries on the field of the same name
/// via the [`EnemyLocationEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.enemy_location().entity_id().find(...)`.
pub struct EnemyLocationEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<EnemyLocation, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EnemyLocationTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `enemy_location`.
    pub fn entity_id(&self) -> EnemyLocationEntityIdUnique<'ctx> {
        EnemyLocationEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EnemyLocationEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<EnemyLocation> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EnemyLocation>("enemy_location");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<EnemyLocation>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EnemyLocation>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `EnemyLocation`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait enemy_locationQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `EnemyLocation`.
    fn enemy_location(&self) -> __sdk::__query_builder::Table<EnemyLocation>;
}

impl enemy_locationQueryTableAccess for __sdk::QueryTableAccessor {
    fn enemy_location(&self) -> __sdk::__query_builder::Table<EnemyLocation> {
        __sdk::__query_builder::Table::new("enemy_location")
    }
}
