// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EnemyLocation {
    pub entity_id: u64,
    pub enemy_type: i32,
    pub x: i32,
    pub z: i32,
    pub region_id: u8,
}

impl __sdk::InModule for EnemyLocation {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `EnemyLocation`.
///
/// Provides typed access to columns for query building.
pub struct EnemyLocationCols {
    pub entity_id: __sdk::__query_builder::Col<EnemyLocation, u64>,
    pub enemy_type: __sdk::__query_builder::Col<EnemyLocation, i32>,
    pub x: __sdk::__query_builder::Col<EnemyLocation, i32>,
    pub z: __sdk::__query_builder::Col<EnemyLocation, i32>,
    pub region_id: __sdk::__query_builder::Col<EnemyLocation, u8>,
}

impl __sdk::__query_builder::HasCols for EnemyLocation {
    type Cols = EnemyLocationCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EnemyLocationCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            enemy_type: __sdk::__query_builder::Col::new(table_name, "enemy_type"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            region_id: __sdk::__query_builder::Col::new(table_name, "region_id"),
        }
    }
}

/// Indexed column accessor struct for the table `EnemyLocation`.
///
/// Provides typed access to indexed columns for query building.
pub struct EnemyLocationIxCols {
    pub enemy_type: __sdk::__query_builder::IxCol<EnemyLocation, i32>,
    pub entity_id: __sdk::__query_builder::IxCol<EnemyLocation, u64>,
    pub region_id: __sdk::__query_builder::IxCol<EnemyLocation, u8>,
}

impl __sdk::__query_builder::HasIxCols for EnemyLocation {
    type IxCols = EnemyLocationIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EnemyLocationIxCols {
            enemy_type: __sdk::__query_builder::IxCol::new(table_name, "enemy_type"),
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            region_id: __sdk::__query_builder::IxCol::new(table_name, "region_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for EnemyLocation {}
