// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ExpiringCraft {
    pub craft_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
}

impl __sdk::InModule for ExpiringCraft {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ExpiringCraft`.
///
/// Provides typed access to columns for query building.
pub struct ExpiringCraftCols {
    pub craft_id: __sdk::__query_builder::Col<ExpiringCraft, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<ExpiringCraft, __sdk::ScheduleAt>,
}

impl __sdk::__query_builder::HasCols for ExpiringCraft {
    type Cols = ExpiringCraftCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ExpiringCraftCols {
            craft_id: __sdk::__query_builder::Col::new(table_name, "craft_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
        }
    }
}

/// Indexed column accessor struct for the table `ExpiringCraft`.
///
/// Provides typed access to indexed columns for query building.
pub struct ExpiringCraftIxCols {
    pub craft_id: __sdk::__query_builder::IxCol<ExpiringCraft, u64>,
}

impl __sdk::__query_builder::HasIxCols for ExpiringCraft {
    type IxCols = ExpiringCraftIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ExpiringCraftIxCols {
            craft_id: __sdk::__query_builder::IxCol::new(table_name, "craft_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ExpiringCraft {}
