// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GrowthTimer {
    pub entity_id: u64,
    pub resource_id: i32,
    pub x: i32,
    pub z: i32,
    pub region_id: u8,
    pub end_timestamp: __sdk::Timestamp,
}

impl __sdk::InModule for GrowthTimer {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GrowthTimer`.
///
/// Provides typed access to columns for query building.
pub struct GrowthTimerCols {
    pub entity_id: __sdk::__query_builder::Col<GrowthTimer, u64>,
    pub resource_id: __sdk::__query_builder::Col<GrowthTimer, i32>,
    pub x: __sdk::__query_builder::Col<GrowthTimer, i32>,
    pub z: __sdk::__query_builder::Col<GrowthTimer, i32>,
    pub region_id: __sdk::__query_builder::Col<GrowthTimer, u8>,
    pub end_timestamp: __sdk::__query_builder::Col<GrowthTimer, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for GrowthTimer {
    type Cols = GrowthTimerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GrowthTimerCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            resource_id: __sdk::__query_builder::Col::new(table_name, "resource_id"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            region_id: __sdk::__query_builder::Col::new(table_name, "region_id"),
            end_timestamp: __sdk::__query_builder::Col::new(table_name, "end_timestamp"),
        }
    }
}

/// Indexed column accessor struct for the table `GrowthTimer`.
///
/// Provides typed access to indexed columns for query building.
pub struct GrowthTimerIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<GrowthTimer, u64>,
    pub region_id: __sdk::__query_builder::IxCol<GrowthTimer, u8>,
}

impl __sdk::__query_builder::HasIxCols for GrowthTimer {
    type IxCols = GrowthTimerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GrowthTimerIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            region_id: __sdk::__query_builder::IxCol::new(table_name, "region_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GrowthTimer {}
