// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::growth_timer_type::GrowthTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `growth_timers`.
///
/// Obtain a handle from the [`GrowthTimersTableAccess::growth_timers`] method on [`super::RemoteTables`],
/// like `ctx.db.growth_timers()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.growth_timers().on_insert(...)`.
pub struct GrowthTimersTableHandle<'ctx> {
    imp: __sdk::TableHandle<GrowthTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `growth_timers`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GrowthTimersTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GrowthTimersTableHandle`], which mediates access to the table `growth_timers`.
    fn growth_timers(&self) -> GrowthTimersTableHandle<'_>;
}

impl GrowthTimersTableAccess for super::RemoteTables {
    fn growth_timers(&self) -> GrowthTimersTableHandle<'_> {
        GrowthTimersTableHandle {
            imp: self.imp.get_table::<GrowthTimer>("growth_timers"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GrowthTimersInsertCallbackId(__sdk::CallbackId);
pub struct GrowthTimersDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GrowthTimersTableHandle<'ctx> {
    type Row = GrowthTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GrowthTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GrowthTimersInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GrowthTimersInsertCallbackId {
        GrowthTimersInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GrowthTimersInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GrowthTimersDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GrowthTimersDeleteCallbackId {
        GrowthTimersDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GrowthTimersDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GrowthTimersUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GrowthTimersTableHandle<'ctx> {
    type UpdateCallbackId = GrowthTimersUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GrowthTimersUpdateCallbackId {
        GrowthTimersUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GrowthTimersUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `growth_timers`,
/// which allows point queries on the field of the same name
/// via the [`GrowthTimersEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.growth_timers().entity_id().find(...)`.
pub struct GrowthTimersEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GrowthTimer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GrowthTimersTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `growth_timers`.
    pub fn entity_id(&self) -> GrowthTimersEntityIdUnique<'ctx> {
        GrowthTimersEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GrowthTimersEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<GrowthTimer> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GrowthTimer>("growth_timers");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GrowthTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GrowthTimer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GrowthTimer`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait growth_timersQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GrowthTimer`.
    fn growth_timers(&self) -> __sdk::__query_builder::Table<GrowthTimer>;
}

impl growth_timersQueryTableAccess for __sdk::QueryTableAccessor {
    fn growth_timers(&self) -> __sdk::__query_builder::Table<GrowthTimer> {
        __sdk::__query_builder::Table::new("growth_timers")
    }
}
