// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::herd_location_type::HerdLocation;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `herd_location`.
///
/// Obtain a handle from the [`HerdLocationTableAccess::herd_location`] method on [`super::RemoteTables`],
/// like `ctx.db.herd_location()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.herd_location().on_insert(...)`.
pub struct HerdLocationTableHandle<'ctx> {
    imp: __sdk::TableHandle<HerdLocation>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `herd_location`.
pub struct HerdLocationTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for HerdLocationTableAccessor {
    type Row = HerdLocation;
    type Handle<'db> = HerdLocationTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.herd_location()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `herd_location`.
///
/// Implemented for [`super::RemoteTables`].
pub trait HerdLocationTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`HerdLocationTableHandle`], which mediates access to the table `herd_location`.
    fn herd_location(&self) -> HerdLocationTableHandle<'_>;
}

impl HerdLocationTableAccess for super::RemoteTables {
    fn herd_location(&self) -> HerdLocationTableHandle<'_> {
        HerdLocationTableHandle {
            imp: self.imp.get_table::<HerdLocation>("herd_location"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct HerdLocationInsertCallbackId(__sdk::CallbackId);
pub struct HerdLocationDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for HerdLocationTableHandle<'ctx> {
    type Row = HerdLocation;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = HerdLocation> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for HerdLocationTableHandle<'ctx> {
    type Row = HerdLocation;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = HerdLocation> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = HerdLocationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HerdLocationInsertCallbackId {
        HerdLocationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: HerdLocationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = HerdLocationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HerdLocationDeleteCallbackId {
        HerdLocationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: HerdLocationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for HerdLocationTableHandle<'ctx> {
    type InsertCallbackId = HerdLocationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HerdLocationInsertCallbackId {
        HerdLocationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: HerdLocationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for HerdLocationTableHandle<'ctx> {
    type DeleteCallbackId = HerdLocationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HerdLocationDeleteCallbackId {
        HerdLocationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: HerdLocationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct HerdLocationUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for HerdLocationTableHandle<'ctx> {
    type UpdateCallbackId = HerdLocationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> HerdLocationUpdateCallbackId {
        HerdLocationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: HerdLocationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for HerdLocationTableHandle<'ctx> {
    type UpdateCallbackId = HerdLocationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> HerdLocationUpdateCallbackId {
        HerdLocationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: HerdLocationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `herd_location`,
/// which allows point queries on the field of the same name
/// via the [`HerdLocationEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.herd_location().entity_id().find(...)`.
pub struct HerdLocationEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<HerdLocation, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> HerdLocationTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `herd_location`.
    pub fn entity_id(&self) -> HerdLocationEntityIdUnique<'ctx> {
        HerdLocationEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> HerdLocationEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<HerdLocation> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<HerdLocation>("herd_location");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<HerdLocation>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<HerdLocation>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `HerdLocation`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait herd_locationQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `HerdLocation`.
    fn herd_location(&self) -> __sdk::__query_builder::Table<HerdLocation>;
}

impl herd_locationQueryTableAccess for __sdk::QueryTableAccessor {
    fn herd_location(&self) -> __sdk::__query_builder::Table<HerdLocation> {
        __sdk::__query_builder::Table::new("herd_location")
    }
}
