// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::growth_timer_update_type::GrowthTimerUpdate;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct InsertGrowthTimersArgs {
    pub timers: Vec<GrowthTimerUpdate>,
}

impl From<InsertGrowthTimersArgs> for super::Reducer {
    fn from(args: InsertGrowthTimersArgs) -> Self {
        Self::InsertGrowthTimers {
            timers: args.timers,
        }
    }
}

impl __sdk::InModule for InsertGrowthTimersArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `insert_growth_timers`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait insert_growth_timers {
    /// Request that the remote module invoke the reducer `insert_growth_timers` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`insert_growth_timers:insert_growth_timers_then`] to run a callback after the reducer completes.
    fn insert_growth_timers(&self, timers: Vec<GrowthTimerUpdate>) -> __sdk::Result<()> {
        self.insert_growth_timers_then(timers, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `insert_growth_timers` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn insert_growth_timers_then(
        &self,
        timers: Vec<GrowthTimerUpdate>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl insert_growth_timers for super::RemoteReducers {
    fn insert_growth_timers_then(
        &self,
        timers: Vec<GrowthTimerUpdate>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(InsertGrowthTimersArgs { timers }, callback)
    }
}
