// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.4.0 (commit b3547448cf06d65c5133e884c9a24f126f92eb12).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod bulk_replace_enemies_reducer;
pub mod bulk_replace_player_states_reducer;
pub mod bulk_replace_players_reducer;
pub mod bulk_replace_resources_reducer;
pub mod delete_enemies_reducer;
pub mod delete_player_states_reducer;
pub mod delete_players_reducer;
pub mod delete_resources_reducer;
pub mod enemy_location_table;
pub mod enemy_location_type;
pub mod init_relay_reducer;
pub mod insert_enemies_reducer;
pub mod insert_resources_reducer;
pub mod mobile_move_update_type;
pub mod move_mobile_entities_reducer;
pub mod player_location_table;
pub mod player_location_type;
pub mod player_rename_update_type;
pub mod player_state_table;
pub mod player_state_type;
pub mod relay_config_type;
pub mod rename_players_reducer;
pub mod resource_location_table;
pub mod resource_location_type;
pub mod set_players_offline_reducer;
pub mod set_players_online_reducer;
pub mod upsert_player_states_reducer;
pub mod upsert_players_reducer;

pub use bulk_replace_enemies_reducer::bulk_replace_enemies;
pub use bulk_replace_player_states_reducer::bulk_replace_player_states;
pub use bulk_replace_players_reducer::bulk_replace_players;
pub use bulk_replace_resources_reducer::bulk_replace_resources;
pub use delete_enemies_reducer::delete_enemies;
pub use delete_player_states_reducer::delete_player_states;
pub use delete_players_reducer::delete_players;
pub use delete_resources_reducer::delete_resources;
pub use enemy_location_table::*;
pub use enemy_location_type::EnemyLocation;
pub use init_relay_reducer::init_relay;
pub use insert_enemies_reducer::insert_enemies;
pub use insert_resources_reducer::insert_resources;
pub use mobile_move_update_type::MobileMoveUpdate;
pub use move_mobile_entities_reducer::move_mobile_entities;
pub use player_location_table::*;
pub use player_location_type::PlayerLocation;
pub use player_rename_update_type::PlayerRenameUpdate;
pub use player_state_table::*;
pub use player_state_type::PlayerState;
pub use relay_config_type::RelayConfig;
pub use rename_players_reducer::rename_players;
pub use resource_location_table::*;
pub use resource_location_type::ResourceLocation;
pub use set_players_offline_reducer::set_players_offline;
pub use set_players_online_reducer::set_players_online;
pub use upsert_player_states_reducer::upsert_player_states;
pub use upsert_players_reducer::upsert_players;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    BulkReplaceEnemies {
        region_id: u8,
        rows: Vec<EnemyLocation>,
        total: u32,
    },
    BulkReplacePlayerStates {
        region_id: u8,
        rows: Vec<PlayerState>,
        total: u32,
    },
    BulkReplacePlayers {
        region_id: u8,
        rows: Vec<PlayerLocation>,
        total: u32,
    },
    BulkReplaceResources {
        region_id: u8,
        rows: Vec<ResourceLocation>,
        total: u32,
    },
    DeleteEnemies {
        entity_ids: Vec<u64>,
    },
    DeletePlayerStates {
        entity_ids: Vec<u64>,
    },
    DeletePlayers {
        entity_ids: Vec<u64>,
    },
    DeleteResources {
        entity_ids: Vec<u64>,
    },
    InitRelay,
    InsertEnemies {
        rows: Vec<EnemyLocation>,
    },
    InsertResources {
        rows: Vec<ResourceLocation>,
    },
    MoveMobileEntities {
        moves: Vec<MobileMoveUpdate>,
    },
    RenamePlayers {
        renames: Vec<PlayerRenameUpdate>,
    },
    SetPlayersOffline {
        entity_ids: Vec<u64>,
    },
    SetPlayersOnline {
        entity_ids: Vec<u64>,
    },
    UpsertPlayerStates {
        rows: Vec<PlayerState>,
    },
    UpsertPlayers {
        rows: Vec<PlayerLocation>,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::BulkReplaceEnemies { .. } => "bulk_replace_enemies",
            Reducer::BulkReplacePlayerStates { .. } => "bulk_replace_player_states",
            Reducer::BulkReplacePlayers { .. } => "bulk_replace_players",
            Reducer::BulkReplaceResources { .. } => "bulk_replace_resources",
            Reducer::DeleteEnemies { .. } => "delete_enemies",
            Reducer::DeletePlayerStates { .. } => "delete_player_states",
            Reducer::DeletePlayers { .. } => "delete_players",
            Reducer::DeleteResources { .. } => "delete_resources",
            Reducer::InitRelay => "init_relay",
            Reducer::InsertEnemies { .. } => "insert_enemies",
            Reducer::InsertResources { .. } => "insert_resources",
            Reducer::MoveMobileEntities { .. } => "move_mobile_entities",
            Reducer::RenamePlayers { .. } => "rename_players",
            Reducer::SetPlayersOffline { .. } => "set_players_offline",
            Reducer::SetPlayersOnline { .. } => "set_players_online",
            Reducer::UpsertPlayerStates { .. } => "upsert_player_states",
            Reducer::UpsertPlayers { .. } => "upsert_players",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::BulkReplaceEnemies {
                region_id,
                rows,
                total,
            } => __sats::bsatn::to_vec(&bulk_replace_enemies_reducer::BulkReplaceEnemiesArgs {
                region_id: region_id.clone(),
                rows: rows.clone(),
                total: total.clone(),
            }),
            Reducer::BulkReplacePlayerStates {
                region_id,
                rows,
                total,
            } => __sats::bsatn::to_vec(
                &bulk_replace_player_states_reducer::BulkReplacePlayerStatesArgs {
                    region_id: region_id.clone(),
                    rows: rows.clone(),
                    total: total.clone(),
                },
            ),
            Reducer::BulkReplacePlayers {
                region_id,
                rows,
                total,
            } => __sats::bsatn::to_vec(&bulk_replace_players_reducer::BulkReplacePlayersArgs {
                region_id: region_id.clone(),
                rows: rows.clone(),
                total: total.clone(),
            }),
            Reducer::BulkReplaceResources {
                region_id,
                rows,
                total,
            } => __sats::bsatn::to_vec(&bulk_replace_resources_reducer::BulkReplaceResourcesArgs {
                region_id: region_id.clone(),
                rows: rows.clone(),
                total: total.clone(),
            }),
            Reducer::DeleteEnemies { entity_ids } => {
                __sats::bsatn::to_vec(&delete_enemies_reducer::DeleteEnemiesArgs {
                    entity_ids: entity_ids.clone(),
                })
            }
            Reducer::DeletePlayerStates { entity_ids } => {
                __sats::bsatn::to_vec(&delete_player_states_reducer::DeletePlayerStatesArgs {
                    entity_ids: entity_ids.clone(),
                })
            }
            Reducer::DeletePlayers { entity_ids } => {
                __sats::bsatn::to_vec(&delete_players_reducer::DeletePlayersArgs {
                    entity_ids: entity_ids.clone(),
                })
            }
            Reducer::DeleteResources { entity_ids } => {
                __sats::bsatn::to_vec(&delete_resources_reducer::DeleteResourcesArgs {
                    entity_ids: entity_ids.clone(),
                })
            }
            Reducer::InitRelay => __sats::bsatn::to_vec(&init_relay_reducer::InitRelayArgs {}),
            Reducer::InsertEnemies { rows } => {
                __sats::bsatn::to_vec(&insert_enemies_reducer::InsertEnemiesArgs {
                    rows: rows.clone(),
                })
            }
            Reducer::InsertResources { rows } => {
                __sats::bsatn::to_vec(&insert_resources_reducer::InsertResourcesArgs {
                    rows: rows.clone(),
                })
            }
            Reducer::MoveMobileEntities { moves } => {
                __sats::bsatn::to_vec(&move_mobile_entities_reducer::MoveMobileEntitiesArgs {
                    moves: moves.clone(),
                })
            }
            Reducer::RenamePlayers { renames } => {
                __sats::bsatn::to_vec(&rename_players_reducer::RenamePlayersArgs {
                    renames: renames.clone(),
                })
            }
            Reducer::SetPlayersOffline { entity_ids } => {
                __sats::bsatn::to_vec(&set_players_offline_reducer::SetPlayersOfflineArgs {
                    entity_ids: entity_ids.clone(),
                })
            }
            Reducer::SetPlayersOnline { entity_ids } => {
                __sats::bsatn::to_vec(&set_players_online_reducer::SetPlayersOnlineArgs {
                    entity_ids: entity_ids.clone(),
                })
            }
            Reducer::UpsertPlayerStates { rows } => {
                __sats::bsatn::to_vec(&upsert_player_states_reducer::UpsertPlayerStatesArgs {
                    rows: rows.clone(),
                })
            }
            Reducer::UpsertPlayers { rows } => {
                __sats::bsatn::to_vec(&upsert_players_reducer::UpsertPlayersArgs {
                    rows: rows.clone(),
                })
            }
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    enemy_location: __sdk::TableUpdate<EnemyLocation>,
    player_location: __sdk::TableUpdate<PlayerLocation>,
    player_state: __sdk::TableUpdate<PlayerState>,
    resource_location: __sdk::TableUpdate<ResourceLocation>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "enemy_location" => db_update
                    .enemy_location
                    .append(enemy_location_table::parse_table_update(table_update)?),
                "player_location" => db_update
                    .player_location
                    .append(player_location_table::parse_table_update(table_update)?),
                "player_state" => db_update
                    .player_state
                    .append(player_state_table::parse_table_update(table_update)?),
                "resource_location" => db_update
                    .resource_location
                    .append(resource_location_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.enemy_location = cache
            .apply_diff_to_table::<EnemyLocation>("enemy_location", &self.enemy_location)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.player_location = cache
            .apply_diff_to_table::<PlayerLocation>("player_location", &self.player_location)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.player_state = cache
            .apply_diff_to_table::<PlayerState>("player_state", &self.player_state)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.resource_location = cache
            .apply_diff_to_table::<ResourceLocation>("resource_location", &self.resource_location)
            .with_updates_by_pk(|row| &row.entity_id);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "enemy_location" => db_update
                    .enemy_location
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player_location" => db_update
                    .player_location
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player_state" => db_update
                    .player_state
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "resource_location" => db_update
                    .resource_location
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "enemy_location" => db_update
                    .enemy_location
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player_location" => db_update
                    .player_location
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player_state" => db_update
                    .player_state
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "resource_location" => db_update
                    .resource_location
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    enemy_location: __sdk::TableAppliedDiff<'r, EnemyLocation>,
    player_location: __sdk::TableAppliedDiff<'r, PlayerLocation>,
    player_state: __sdk::TableAppliedDiff<'r, PlayerState>,
    resource_location: __sdk::TableAppliedDiff<'r, ResourceLocation>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<EnemyLocation>(
            "enemy_location",
            &self.enemy_location,
            event,
        );
        callbacks.invoke_table_row_callbacks::<PlayerLocation>(
            "player_location",
            &self.player_location,
            event,
        );
        callbacks.invoke_table_row_callbacks::<PlayerState>(
            "player_state",
            &self.player_state,
            event,
        );
        callbacks.invoke_table_row_callbacks::<ResourceLocation>(
            "resource_location",
            &self.resource_location,
            event,
        );
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        enemy_location_table::register_table(client_cache);
        player_location_table::register_table(client_cache);
        player_state_table::register_table(client_cache);
        resource_location_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "enemy_location",
        "player_location",
        "player_state",
        "resource_location",
    ];
}
