// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerLocation {
    pub entity_id: u64,
    pub x: i32,
    pub z: i32,
    pub region_id: u8,
}

impl __sdk::InModule for PlayerLocation {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerLocation`.
///
/// Provides typed access to columns for query building.
pub struct PlayerLocationCols {
    pub entity_id: __sdk::__query_builder::Col<PlayerLocation, u64>,
    pub x: __sdk::__query_builder::Col<PlayerLocation, i32>,
    pub z: __sdk::__query_builder::Col<PlayerLocation, i32>,
    pub region_id: __sdk::__query_builder::Col<PlayerLocation, u8>,
}

impl __sdk::__query_builder::HasCols for PlayerLocation {
    type Cols = PlayerLocationCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerLocationCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            region_id: __sdk::__query_builder::Col::new(table_name, "region_id"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerLocation`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerLocationIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<PlayerLocation, u64>,
    pub region_id: __sdk::__query_builder::IxCol<PlayerLocation, u8>,
}

impl __sdk::__query_builder::HasIxCols for PlayerLocation {
    type IxCols = PlayerLocationIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerLocationIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            region_id: __sdk::__query_builder::IxCol::new(table_name, "region_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerLocation {}
