// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::recipe_meta_type::RecipeMeta;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `recipe_meta`.
///
/// Obtain a handle from the [`RecipeMetaTableAccess::recipe_meta`] method on [`super::RemoteTables`],
/// like `ctx.db.recipe_meta()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.recipe_meta().on_insert(...)`.
pub struct RecipeMetaTableHandle<'ctx> {
    imp: __sdk::TableHandle<RecipeMeta>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `recipe_meta`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RecipeMetaTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RecipeMetaTableHandle`], which mediates access to the table `recipe_meta`.
    fn recipe_meta(&self) -> RecipeMetaTableHandle<'_>;
}

impl RecipeMetaTableAccess for super::RemoteTables {
    fn recipe_meta(&self) -> RecipeMetaTableHandle<'_> {
        RecipeMetaTableHandle {
            imp: self.imp.get_table::<RecipeMeta>("recipe_meta"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RecipeMetaInsertCallbackId(__sdk::CallbackId);
pub struct RecipeMetaDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RecipeMetaTableHandle<'ctx> {
    type Row = RecipeMeta;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RecipeMeta> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RecipeMetaInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RecipeMetaInsertCallbackId {
        RecipeMetaInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RecipeMetaInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RecipeMetaDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RecipeMetaDeleteCallbackId {
        RecipeMetaDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RecipeMetaDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct RecipeMetaUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RecipeMetaTableHandle<'ctx> {
    type UpdateCallbackId = RecipeMetaUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RecipeMetaUpdateCallbackId {
        RecipeMetaUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RecipeMetaUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `recipe_meta`,
/// which allows point queries on the field of the same name
/// via the [`RecipeMetaIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.recipe_meta().id().find(...)`.
pub struct RecipeMetaIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RecipeMeta, i32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RecipeMetaTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `recipe_meta`.
    pub fn id(&self) -> RecipeMetaIdUnique<'ctx> {
        RecipeMetaIdUnique {
            imp: self.imp.get_unique_constraint::<i32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RecipeMetaIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i32) -> Option<RecipeMeta> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RecipeMeta>("recipe_meta");
    _table.add_unique_constraint::<i32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RecipeMeta>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RecipeMeta>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RecipeMeta`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait recipe_metaQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RecipeMeta`.
    fn recipe_meta(&self) -> __sdk::__query_builder::Table<RecipeMeta>;
}

impl recipe_metaQueryTableAccess for __sdk::QueryTableAccessor {
    fn recipe_meta(&self) -> __sdk::__query_builder::Table<RecipeMeta> {
        __sdk::__query_builder::Table::new("recipe_meta")
    }
}
