// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RecipeMeta {
    pub id: i32,
    pub effort_required: i32,
    pub skill_id: i32,
    pub exp_per_progress: f32,
    pub level_required: i32,
}

impl __sdk::InModule for RecipeMeta {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RecipeMeta`.
///
/// Provides typed access to columns for query building.
pub struct RecipeMetaCols {
    pub id: __sdk::__query_builder::Col<RecipeMeta, i32>,
    pub effort_required: __sdk::__query_builder::Col<RecipeMeta, i32>,
    pub skill_id: __sdk::__query_builder::Col<RecipeMeta, i32>,
    pub exp_per_progress: __sdk::__query_builder::Col<RecipeMeta, f32>,
    pub level_required: __sdk::__query_builder::Col<RecipeMeta, i32>,
}

impl __sdk::__query_builder::HasCols for RecipeMeta {
    type Cols = RecipeMetaCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RecipeMetaCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            effort_required: __sdk::__query_builder::Col::new(table_name, "effort_required"),
            skill_id: __sdk::__query_builder::Col::new(table_name, "skill_id"),
            exp_per_progress: __sdk::__query_builder::Col::new(table_name, "exp_per_progress"),
            level_required: __sdk::__query_builder::Col::new(table_name, "level_required"),
        }
    }
}

/// Indexed column accessor struct for the table `RecipeMeta`.
///
/// Provides typed access to indexed columns for query building.
pub struct RecipeMetaIxCols {
    pub id: __sdk::__query_builder::IxCol<RecipeMeta, i32>,
}

impl __sdk::__query_builder::HasIxCols for RecipeMeta {
    type IxCols = RecipeMetaIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RecipeMetaIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RecipeMeta {}
