// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ReconcileCraftsArgs {
    pub region_id: u8,
    pub craft_ids: Vec<u64>,
}

impl From<ReconcileCraftsArgs> for super::Reducer {
    fn from(args: ReconcileCraftsArgs) -> Self {
        Self::ReconcileCrafts {
            region_id: args.region_id,
            craft_ids: args.craft_ids,
        }
    }
}

impl __sdk::InModule for ReconcileCraftsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `reconcile_crafts`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait reconcile_crafts {
    /// Request that the remote module invoke the reducer `reconcile_crafts` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`reconcile_crafts:reconcile_crafts_then`] to run a callback after the reducer completes.
    fn reconcile_crafts(&self, region_id: u8, craft_ids: Vec<u64>) -> __sdk::Result<()> {
        self.reconcile_crafts_then(region_id, craft_ids, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `reconcile_crafts` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn reconcile_crafts_then(
        &self,
        region_id: u8,
        craft_ids: Vec<u64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl reconcile_crafts for super::RemoteReducers {
    fn reconcile_crafts_then(
        &self,
        region_id: u8,
        craft_ids: Vec<u64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ReconcileCraftsArgs {
                region_id,
                craft_ids,
            },
            callback,
        )
    }
}
