// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Region {
    pub id: u8,
    pub name: String,
    pub min_chunk_x: u16,
    pub min_chunk_z: u16,
    pub width_chunks: u16,
    pub height_chunks: u16,
    pub initialized: bool,
    pub allow_players: bool,
    pub allow_player_spawns: bool,
}

impl __sdk::InModule for Region {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Region`.
///
/// Provides typed access to columns for query building.
pub struct RegionCols {
    pub id: __sdk::__query_builder::Col<Region, u8>,
    pub name: __sdk::__query_builder::Col<Region, String>,
    pub min_chunk_x: __sdk::__query_builder::Col<Region, u16>,
    pub min_chunk_z: __sdk::__query_builder::Col<Region, u16>,
    pub width_chunks: __sdk::__query_builder::Col<Region, u16>,
    pub height_chunks: __sdk::__query_builder::Col<Region, u16>,
    pub initialized: __sdk::__query_builder::Col<Region, bool>,
    pub allow_players: __sdk::__query_builder::Col<Region, bool>,
    pub allow_player_spawns: __sdk::__query_builder::Col<Region, bool>,
}

impl __sdk::__query_builder::HasCols for Region {
    type Cols = RegionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RegionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            min_chunk_x: __sdk::__query_builder::Col::new(table_name, "min_chunk_x"),
            min_chunk_z: __sdk::__query_builder::Col::new(table_name, "min_chunk_z"),
            width_chunks: __sdk::__query_builder::Col::new(table_name, "width_chunks"),
            height_chunks: __sdk::__query_builder::Col::new(table_name, "height_chunks"),
            initialized: __sdk::__query_builder::Col::new(table_name, "initialized"),
            allow_players: __sdk::__query_builder::Col::new(table_name, "allow_players"),
            allow_player_spawns: __sdk::__query_builder::Col::new(
                table_name,
                "allow_player_spawns",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `Region`.
///
/// Provides typed access to indexed columns for query building.
pub struct RegionIxCols {
    pub id: __sdk::__query_builder::IxCol<Region, u8>,
}

impl __sdk::__query_builder::HasIxCols for Region {
    type IxCols = RegionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RegionIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Region {}
