// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ResourceLocation {
    pub entity_id: u64,
    pub resource_id: i32,
    pub region_id: u8,
    pub x: i32,
    pub z: i32,
}

impl __sdk::InModule for ResourceLocation {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ResourceLocation`.
///
/// Provides typed access to columns for query building.
pub struct ResourceLocationCols {
    pub entity_id: __sdk::__query_builder::Col<ResourceLocation, u64>,
    pub resource_id: __sdk::__query_builder::Col<ResourceLocation, i32>,
    pub region_id: __sdk::__query_builder::Col<ResourceLocation, u8>,
    pub x: __sdk::__query_builder::Col<ResourceLocation, i32>,
    pub z: __sdk::__query_builder::Col<ResourceLocation, i32>,
}

impl __sdk::__query_builder::HasCols for ResourceLocation {
    type Cols = ResourceLocationCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ResourceLocationCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            resource_id: __sdk::__query_builder::Col::new(table_name, "resource_id"),
            region_id: __sdk::__query_builder::Col::new(table_name, "region_id"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
        }
    }
}

/// Indexed column accessor struct for the table `ResourceLocation`.
///
/// Provides typed access to indexed columns for query building.
pub struct ResourceLocationIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<ResourceLocation, u64>,
    pub region_id: __sdk::__query_builder::IxCol<ResourceLocation, u8>,
    pub resource_id: __sdk::__query_builder::IxCol<ResourceLocation, i32>,
}

impl __sdk::__query_builder::HasIxCols for ResourceLocation {
    type IxCols = ResourceLocationIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ResourceLocationIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            region_id: __sdk::__query_builder::IxCol::new(table_name, "region_id"),
            resource_id: __sdk::__query_builder::IxCol::new(table_name, "resource_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ResourceLocation {}
