// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::resource_location_type::ResourceLocation;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `resource_location`.
///
/// Obtain a handle from the [`ResourceLocationTableAccess::resource_location`] method on [`super::RemoteTables`],
/// like `ctx.db.resource_location()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.resource_location().on_insert(...)`.
pub struct ResourceLocationTableHandle<'ctx> {
    imp: __sdk::TableHandle<ResourceLocation>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `resource_location`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ResourceLocationTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ResourceLocationTableHandle`], which mediates access to the table `resource_location`.
    fn resource_location(&self) -> ResourceLocationTableHandle<'_>;
}

impl ResourceLocationTableAccess for super::RemoteTables {
    fn resource_location(&self) -> ResourceLocationTableHandle<'_> {
        ResourceLocationTableHandle {
            imp: self.imp.get_table::<ResourceLocation>("resource_location"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ResourceLocationInsertCallbackId(__sdk::CallbackId);
pub struct ResourceLocationDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ResourceLocationTableHandle<'ctx> {
    type Row = ResourceLocation;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ResourceLocation> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ResourceLocationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ResourceLocationInsertCallbackId {
        ResourceLocationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ResourceLocationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ResourceLocationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ResourceLocationDeleteCallbackId {
        ResourceLocationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ResourceLocationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ResourceLocationUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ResourceLocationTableHandle<'ctx> {
    type UpdateCallbackId = ResourceLocationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ResourceLocationUpdateCallbackId {
        ResourceLocationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ResourceLocationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `resource_location`,
/// which allows point queries on the field of the same name
/// via the [`ResourceLocationEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.resource_location().entity_id().find(...)`.
pub struct ResourceLocationEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ResourceLocation, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ResourceLocationTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `resource_location`.
    pub fn entity_id(&self) -> ResourceLocationEntityIdUnique<'ctx> {
        ResourceLocationEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ResourceLocationEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ResourceLocation> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ResourceLocation>("resource_location");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ResourceLocation>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ResourceLocation>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ResourceLocation`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait resource_locationQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ResourceLocation`.
    fn resource_location(&self) -> __sdk::__query_builder::Table<ResourceLocation>;
}

impl resource_locationQueryTableAccess for __sdk::QueryTableAccessor {
    fn resource_location(&self) -> __sdk::__query_builder::Table<ResourceLocation> {
        __sdk::__query_builder::Table::new("resource_location")
    }
}
