// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ScheduleCraftExpiryArgs {
    pub craft_ids: Vec<u64>,
}

impl From<ScheduleCraftExpiryArgs> for super::Reducer {
    fn from(args: ScheduleCraftExpiryArgs) -> Self {
        Self::ScheduleCraftExpiry {
            craft_ids: args.craft_ids,
        }
    }
}

impl __sdk::InModule for ScheduleCraftExpiryArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `schedule_craft_expiry`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait schedule_craft_expiry {
    /// Request that the remote module invoke the reducer `schedule_craft_expiry` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`schedule_craft_expiry:schedule_craft_expiry_then`] to run a callback after the reducer completes.
    fn schedule_craft_expiry(&self, craft_ids: Vec<u64>) -> __sdk::Result<()> {
        self.schedule_craft_expiry_then(craft_ids, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `schedule_craft_expiry` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn schedule_craft_expiry_then(
        &self,
        craft_ids: Vec<u64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl schedule_craft_expiry for super::RemoteReducers {
    fn schedule_craft_expiry_then(
        &self,
        craft_ids: Vec<u64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ScheduleCraftExpiryArgs { craft_ids }, callback)
    }
}
