// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::claim_owner_update_type::ClaimOwnerUpdate;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetClaimOwnersArgs {
    pub updates: Vec<ClaimOwnerUpdate>,
}

impl From<SetClaimOwnersArgs> for super::Reducer {
    fn from(args: SetClaimOwnersArgs) -> Self {
        Self::SetClaimOwners {
            updates: args.updates,
        }
    }
}

impl __sdk::InModule for SetClaimOwnersArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_claim_owners`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_claim_owners {
    /// Request that the remote module invoke the reducer `set_claim_owners` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_claim_owners:set_claim_owners_then`] to run a callback after the reducer completes.
    fn set_claim_owners(&self, updates: Vec<ClaimOwnerUpdate>) -> __sdk::Result<()> {
        self.set_claim_owners_then(updates, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_claim_owners` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_claim_owners_then(
        &self,
        updates: Vec<ClaimOwnerUpdate>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_claim_owners for super::RemoteReducers {
    fn set_claim_owners_then(
        &self,
        updates: Vec<ClaimOwnerUpdate>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetClaimOwnersArgs { updates }, callback)
    }
}
