// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetPlayersOnlineArgs {
    pub entity_ids: Vec<u64>,
}

impl From<SetPlayersOnlineArgs> for super::Reducer {
    fn from(args: SetPlayersOnlineArgs) -> Self {
        Self::SetPlayersOnline {
            entity_ids: args.entity_ids,
        }
    }
}

impl __sdk::InModule for SetPlayersOnlineArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_players_online`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_players_online {
    /// Request that the remote module invoke the reducer `set_players_online` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_players_online:set_players_online_then`] to run a callback after the reducer completes.
    fn set_players_online(&self, entity_ids: Vec<u64>) -> __sdk::Result<()> {
        self.set_players_online_then(entity_ids, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_players_online` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_players_online_then(
        &self,
        entity_ids: Vec<u64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_players_online for super::RemoteReducers {
    fn set_players_online_then(
        &self,
        entity_ids: Vec<u64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetPlayersOnlineArgs { entity_ids }, callback)
    }
}
