// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::craft_public_update_type::CraftPublicUpdate;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TogglePublicArgs {
    pub updates: Vec<CraftPublicUpdate>,
}

impl From<TogglePublicArgs> for super::Reducer {
    fn from(args: TogglePublicArgs) -> Self {
        Self::TogglePublic {
            updates: args.updates,
        }
    }
}

impl __sdk::InModule for TogglePublicArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `toggle_public`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait toggle_public {
    /// Request that the remote module invoke the reducer `toggle_public` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`toggle_public:toggle_public_then`] to run a callback after the reducer completes.
    fn toggle_public(&self, updates: Vec<CraftPublicUpdate>) -> __sdk::Result<()> {
        self.toggle_public_then(updates, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `toggle_public` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn toggle_public_then(
        &self,
        updates: Vec<CraftPublicUpdate>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl toggle_public for super::RemoteReducers {
    fn toggle_public_then(
        &self,
        updates: Vec<CraftPublicUpdate>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(TogglePublicArgs { updates }, callback)
    }
}
