// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_location_type::PlayerLocation;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertPlayersArgs {
    pub rows: Vec<PlayerLocation>,
}

impl From<UpsertPlayersArgs> for super::Reducer {
    fn from(args: UpsertPlayersArgs) -> Self {
        Self::UpsertPlayers { rows: args.rows }
    }
}

impl __sdk::InModule for UpsertPlayersArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_players`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_players {
    /// Request that the remote module invoke the reducer `upsert_players` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`upsert_players:upsert_players_then`] to run a callback after the reducer completes.
    fn upsert_players(&self, rows: Vec<PlayerLocation>) -> __sdk::Result<()> {
        self.upsert_players_then(rows, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `upsert_players` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn upsert_players_then(
        &self,
        rows: Vec<PlayerLocation>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_players for super::RemoteReducers {
    fn upsert_players_then(
        &self,
        rows: Vec<PlayerLocation>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpsertPlayersArgs { rows }, callback)
    }
}
