// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::claim_supply_type::ClaimSupply;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertClaimSupplyArgs {
    pub rows: Vec<ClaimSupply>,
}

impl From<UpsertClaimSupplyArgs> for super::Reducer {
    fn from(args: UpsertClaimSupplyArgs) -> Self {
        Self::UpsertClaimSupply { rows: args.rows }
    }
}

impl __sdk::InModule for UpsertClaimSupplyArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_claim_supply`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_claim_supply {
    /// Request that the remote module invoke the reducer `upsert_claim_supply` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`upsert_claim_supply:upsert_claim_supply_then`] to run a callback after the reducer completes.
    fn upsert_claim_supply(&self, rows: Vec<ClaimSupply>) -> __sdk::Result<()> {
        self.upsert_claim_supply_then(rows, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `upsert_claim_supply` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn upsert_claim_supply_then(
        &self,
        rows: Vec<ClaimSupply>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_claim_supply for super::RemoteReducers {
    fn upsert_claim_supply_then(
        &self,
        rows: Vec<ClaimSupply>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpsertClaimSupplyArgs { rows }, callback)
    }
}
