// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_state_type::PlayerState;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertPlayerStatesArgs {
    pub rows: Vec<PlayerState>,
}

impl From<UpsertPlayerStatesArgs> for super::Reducer {
    fn from(args: UpsertPlayerStatesArgs) -> Self {
        Self::UpsertPlayerStates { rows: args.rows }
    }
}

impl __sdk::InModule for UpsertPlayerStatesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_player_states`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_player_states {
    /// Request that the remote module invoke the reducer `upsert_player_states` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`upsert_player_states:upsert_player_states_then`] to run a callback after the reducer completes.
    fn upsert_player_states(&self, rows: Vec<PlayerState>) -> __sdk::Result<()> {
        self.upsert_player_states_then(rows, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `upsert_player_states` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn upsert_player_states_then(
        &self,
        rows: Vec<PlayerState>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_player_states for super::RemoteReducers {
    fn upsert_player_states_then(
        &self,
        rows: Vec<PlayerState>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpsertPlayerStatesArgs { rows }, callback)
    }
}
