// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::recipe_meta_type::RecipeMeta;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertRecipeMetaArgs {
    pub rows: Vec<RecipeMeta>,
}

impl From<UpsertRecipeMetaArgs> for super::Reducer {
    fn from(args: UpsertRecipeMetaArgs) -> Self {
        Self::UpsertRecipeMeta { rows: args.rows }
    }
}

impl __sdk::InModule for UpsertRecipeMetaArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_recipe_meta`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_recipe_meta {
    /// Request that the remote module invoke the reducer `upsert_recipe_meta` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`upsert_recipe_meta:upsert_recipe_meta_then`] to run a callback after the reducer completes.
    fn upsert_recipe_meta(&self, rows: Vec<RecipeMeta>) -> __sdk::Result<()> {
        self.upsert_recipe_meta_then(rows, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `upsert_recipe_meta` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn upsert_recipe_meta_then(
        &self,
        rows: Vec<RecipeMeta>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_recipe_meta for super::RemoteReducers {
    fn upsert_recipe_meta_then(
        &self,
        rows: Vec<RecipeMeta>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpsertRecipeMetaArgs { rows }, callback)
    }
}
