// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::enemy_location_type::EnemyLocation;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertEnemiesArgs {
    pub rows: Vec<EnemyLocation>,
}

impl From<UpsertEnemiesArgs> for super::Reducer {
    fn from(args: UpsertEnemiesArgs) -> Self {
        Self::UpsertEnemies { rows: args.rows }
    }
}

impl __sdk::InModule for UpsertEnemiesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_enemies`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_enemies {
    /// Request that the remote module invoke the reducer `upsert_enemies` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`upsert_enemies:upsert_enemies_then`] to run a callback after the reducer completes.
    fn upsert_enemies(&self, rows: Vec<EnemyLocation>) -> __sdk::Result<()> {
        self.upsert_enemies_then(rows, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `upsert_enemies` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn upsert_enemies_then(
        &self,
        rows: Vec<EnemyLocation>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_enemies for super::RemoteReducers {
    fn upsert_enemies_then(
        &self,
        rows: Vec<EnemyLocation>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpsertEnemiesArgs { rows }, callback)
    }
}
