// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::herd_location_type::HerdLocation;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertHerdsArgs {
    pub rows: Vec<HerdLocation>,
}

impl From<UpsertHerdsArgs> for super::Reducer {
    fn from(args: UpsertHerdsArgs) -> Self {
        Self::UpsertHerds { rows: args.rows }
    }
}

impl __sdk::InModule for UpsertHerdsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_herds`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_herds {
    /// Request that the remote module invoke the reducer `upsert_herds` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`upsert_herds:upsert_herds_then`] to run a callback after the reducer completes.
    fn upsert_herds(&self, rows: Vec<HerdLocation>) -> __sdk::Result<()> {
        self.upsert_herds_then(rows, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `upsert_herds` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn upsert_herds_then(
        &self,
        rows: Vec<HerdLocation>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_herds for super::RemoteReducers {
    fn upsert_herds_then(
        &self,
        rows: Vec<HerdLocation>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpsertHerdsArgs { rows }, callback)
    }
}
