input_dir = "/data/"
output_dir = "/data/"
run_on_complete = "/app/upload_tiles.sh {}"

[[tasks]]
renderer = "terrain"
# daily, offset ~5 min from the terrain dump tasks
schedule = "0 0 4 * * *"

[[tasks]]
renderer = "game"
# daily, staggered after terrain
schedule = "0 10 4 * * *"

[[tasks]]
renderer = "roads"
# hourly, shortly after all paving dump tasks, but before terrain rendering
schedule = "0 50 * * * *"
